eval "$(/opt/homebrew/bin/brew shellenv)"

# 1Password Connect Configuration
# MOVIDO PARA ~/.config/op/op_config.sh
# Para usar Connect, use: op-connect-enable
# Para usar CLI (padrão), use: op (já funciona automaticamente)
# export OP_CONNECT_TOKEN='eyJhbGciOiJFUzI1NiIsImtpZCI6ImNvNnU1ZGE2M2Jwem9mbjZ6M25kczV5Nm1pIiwidHlwIjoiSldUIn0.eyIxcGFzc3dvcmQuY29tL2F1dWlkIjoiUlRUVzNRWUQ2RkdTQkZUTUVUTTYzSE5OTzQiLCIxcGFzc3dvcmQuY29tL3Rva2VuIjoiQmxVV1preWpuOWFVVVJQSEE5OGh0Rm5aWTA0QkFyMGoiLCIxcGFzc3dvcmQuY29tL2Z0cyI6WyJ2YXVsdGFjY2VzcyJdLCIxcGFzc3dvcmQuY29tL3Z0cyI6W3sidSI6ImdrcHNiZ2l6bGtzMnprbnd6cXBwcG5iMnplIiwiYSI6NDk2fV0sImF1ZCI6WyJjb20uMXBhc3N3b3JkLmNvbm5lY3QiXSwic3ViIjoiVTczR1RSRzJHQkQ2UkRGQVVIQlBBV0NKTlEiLCJpYXQiOjE3NjE0MDg4NjcsImlzcyI6ImNvbS4xcGFzc3dvcmQuYjUiLCJqdGkiOiI0c2ZzNnpveTZudWJ1eHJxaDRiaGE2YjM2NCJ9.o8ZzCONl-qNkYu6HOCZBIfNVMKmEJvv-VaAlRQ8hROjRI0jOBpRUt0WbTba0VriCevMWDiPrywQOwr3eLKzW_g'
# export OP_CONNECT_HOST='http://localhost:8080'
